runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "service_account.json"

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
